@url = https://localhost:5001

POST {{url}}/api/vehicles HTTP/1.1
content-type: application/json

{
    "modelId":9,
    "isRegistered": true,
    contact:{
        "name": "sample-new",
    "phone": "9087651321",
    "email": "dip4k@github.io"
    },
    features:[1,2,3]
}

###
PUT  {{url}}/api/vehicles/3 HTTP/1.1
content-type: application/json

{
    "modelId":2,
    "isRegistered": true,
    contact:{
        "name": "sample-update",
    "phone": "9087654381",
    "email": "dip4k@hackerearth.com"
    },
    features:[1,2,3]
}

###

GET {{url}}/api/vehicles/6

###
DELETE {{url}}/api/vehicles/2

###

GET {{url}}/api/makes HTTP/1.1

###

GET {{url}}/api/vehicles
###

GET https://localhost:44343/api/makes
###
GET {{url}}/api/features HTTP/1.1

###

GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

@curl = https://localhost:44318/api/customers
Get {{curl}}

###

POST {{curl}}/login
content-type: application/json

{
    "userName": "dipak",
    "password": "qwerty"
  }
